# Site Settings
baseurl: ""
url : "https://cvrcantillan.netlify.app"

# Blog Settings
theme_settings :
  title : Roberto Cantillan CV
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/IMG_20200728_155710.jpg
    username : Roberto Cantillan Carrasco
    description : Sociólogo, Magister en Ciencias Sociales por la Universidad de Santiago de Chile. Miembro del laboratorio de Análisis de Redes Sociales. 
    experience :
      - start : 2020
        end : Hasta la fecha
        experience : Asistente CICLOS - UDP 
      - start : 2018-03-01
        end : Hasta la fecha
        experience : FONDECYT 1171426, Asistente técnico
      - start : 2018-07-01
        end : 2020-01-28
        experience : Universidad de Santiago de Chile, Psi. Profesor
      - start : 2019-06-01
        end : 2020-03-15
        experience : Instituto de Seguridad del Trabajo, Analista 
      
    skills : 
      - skill : markdown
        value : 65
      - skill : R (programmer) 
        value : 65 
      - skill : idioma (inglés) 
        value : 80 
      - skill : Social Network Analysis
        value : 65
      - skill : Statistics
        value : 65 
      - skill : Qualitative Methodology
        value : 60
       
        
  # Icons
  icons :
    email: roberto.cantillan@usach.cl # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/roberto-cantillan-carrasco-67620517b/ # Full URL 
    github: rcantillan77
    gitlab: roberto.cantillan
    researchgate: profile/Roberto_Cantillan_Carrasco
    googlescholar: citations?user=xZkAmvAAAAAJ&hl=es
    zotero: rcantillan/library
    cv: CURRICULUM VITAE RC.pdf
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
