# Site Settings
baseurl: ""
url : "https://cvrcantillan.netlify.app/portfolio"

# Blog Settings
theme_settings :
  title : Roberto Cantillan CV
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Roberto Cantillan Carrasco
    description : Sociólogo, Magister en Ciencias Sociales por la Universidad de Santiago de Chile. Miembro del laboratorio de Análisis de Redes Sociales. 
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
      - start : 2019-08-02
        end : 2020-05-02
        experience : Universidad de Santiago de Chile. Profesor. 
      
    skills : 
      - skill : markdown
        value : 50
      - skill : R 
        value : 55 
      - skill : idioma (inglés) 
        value : 80 
       
        
  # Icons
  icons :
    email: roberto.cantillan@usach.cl # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/roberto-cantillan-carrasco-67620517b/ # Full URL 
    github: rcantillan77
    gitlab: roberto.cantillan
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
